### ISSUE TITLE
audio sync problems

### ISSUE THREAD

**Issue by raxip** [toru173/Lenkeng373#2]
I'd like to start by saying this is a very nice piece of work.  It works, but I'm running into audio sync issues.  No matter how I tinker with the delay argument I'm getting audio out of sync and the amount varies.  Any ideas?

edit:  I should share what I have found/tried so far...
My test rig is a dual xeon e5-2670 (16 physical cores/32 logical HT) with 128GB RAM.  Running Ubuntu 16.04.  I'm writing the audio and video fifo, as well as the output file to a ram drive (/dev/shm) to eliminate disk access as a bottleneck.
When I run with default ffmpeg settings I immediately see warnings about "Thread message queue blocking; consider raising the thread_queue_size option (current value: 8)" for both the audio and video stream.
I don't know what exactly ffmpeg is spitting to stdout, but it appears to be dropping frames.  The audio/video sync is spot-on in this mode, but you can tell frames are missing because things appear jerky.

If I use the thread_queue_size ffmpeg arg and set it to something high like 512, I no longer get any complaints about queue blocking nor frame drops.  The resulting video is silky smooth, however, the audio is badly out of sync.

**Comment by toru173** [comment]
Hi raxip,

I haven't looked over the code for a long time. I've always run the implementation on very low-end hardware, so never bothered optimising for FFMPEG throughput, just for latency. I've been meaning to go back over the code though.

Is your audio ahead or behind? I suspect with your settings the video encode portion in FFMPEG takes longer, so causes a delay.

I might rework the code a little while we're troubleshooting!

**Comment by raxip** [comment]
It tends to start out close to in sync, but the audio gets more and more ahead of the video.

**Comment by toru173** [comment]
Hi Raxip,

It looks like the ffmpeg thread gets more and more behind as it's encoding the video stream, and the audio fifo keeps on track because the bitrate/timing is specified in ffmpeg args. Try changing the ffmpeg args such that it only copies the audio and video track - perhaps encapsulating them in a matroska container - and THEN performs a transcode step. You might have more luck. As it stands, I put the code up for my future reference and it's not an actively maintained project. I don't even remember where my lenkeng is!
